version: "3.8"

volumes:
  mariadb:
    name: mariadb
  wordpress:
    name: wordpress

networks:
  inception:
    name: inception

services:
#mariadb
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
#nginx
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always