version: "3.8"

volumes:
  mariadb:
    name: mariadb
  wordpress:
    name: wordpress

networks:
  inception:
    name: inception

services:
#mariadb
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

#nginx
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

#wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always