name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build MariaDB Image
      run: docker build mariadb --file mariadb/Dockerfile --tag mariadb:$(date +%y.%m.%d)

    - name: Build Nginx Image
      run: docker build nginx --file nginx/Dockerfile --tag nginx:$(date +%y.%m.%d)

    - name: Build WordPress Image
      run: docker build wordpress --file wordpress/Dockerfile --tag wordpress:$(date +%y.%m.%d)

    - name: Push Images
      run: |
        docker tag mariadb:$(date +%y.%m.%d) ${{ secrets.DOCKER_USERNAME }}/mariadb:$(date +%y.%m.%d)
        docker tag nginx:$(date +%y.%m.%d) ${{ secrets.DOCKER_USERNAME }}/nginx:$(date +%y.%m.%d)
        docker tag wordpress:$(date +%y.%m.%d) ${{ secrets.DOCKER_USERNAME }}/wordpress:$(date +%y.%m.%d)

        docker push ${{ secrets.DOCKER_USERNAME }}/mariadb:$(date +%y.%m.%d)
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx:$(date +%y.%m.%d)
        docker push ${{ secrets.DOCKER_USERNAME }}/wordpress:$(date +%y.%m.%d)